modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/Officialy/TFC-Metallurgy/issues"

[[mods]]
modId="tfc_metallurgy"
version="1.0.2"
displayName="TFC Metallurgy"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tfc_metallurgy"
authors="OfficialyMax (Current), Hyperbaton (Added some metals), Mrthomas20121 (1.18 version)"
description='''
Add metals and ores from other mods and science itself to TFC.
'''

[[dependencies.tfc_metallurgy]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.tfc_metallurgy]]
    modId="tfc"
    mandatory=true
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"