# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
org.gradle.caching=false

mod_version=1.1.0

# Minecraft
minecraft_version=1.21.1

# NeoForge
neo_version=21.1.219

# TFC
tfc_version=8063726
tfc_version_range=[4.1.0,)

jade_version=7545219

# Patchouli - TODO: find 1.21.1 NeoForge version
# patchouli_version=
